### ISSUE TITLE
Not able to generate ckpt file

### ISSUE THREAD

**Issue by DefCon-init** [visitor9999th/Tensorflow_GP-GAN#6]
I followed all the steps as said in Readme. Still, the ckpt file is not found.

**Comment by VicenteAlex** [comment]
The ckpt is generated in line 238 of train_blending_gan.py

"if cycle != 0 and cycle % args.snapshot_interval == 0:
                saver.save(sess=sess, save_path=model_save_path, global_step=encode_step_cycle(step, cycle))"

So what is your "snapshot_interval"? The default is 500, did you train the network for more steps than "snapshot_interval"?

**Comment by DefCon-init** [comment]
Thanks for pointing this out. I was able to generate the .ckpt file after changing the snapshot_interval
